### PR TITLE
Update event-list.component.ts DOM text reinterpreted as HTML

### PR DESCRIPTION
**Pull request by Shivam7-1**
By using innerText, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML.

### CODE REVIEW

**Comment by Shivam7-1** [comment]
Hi @evil-shrike Could You Please Review This PR 
Thanks

**Comment by Shivam7-1** [comment]
Hi @evil-shrike Thanks For Reviewing PR's
Instead of using `innerText` or `innerHtml`  Can we use `textcontent` 
I think it could be work fine ?
Thanks

**Comment by evil-shrike** [comment]
Maybe, but may I what issues you're facing (so that innerHTML doesn't work for you)?

**Comment by Shivam7-1** [comment]
Hi @evil-shrike Thanks For Reviewing 
It works Fine But I think it would be More Secure and Provide Security Enhancement To the Code 
Thanks

**Comment by evil-shrike** [comment]
Understand but the project isn't in a state where I'm ready to introduce changes 'just-in-case', sorry

**Pull request closed without merging**
